apiVersion: v1
kind: Service
metadata:
  name: hdoev-web-admin-lb
  annotations:
    services.beta.kubernetes.io/aws-load-balancer-type: nlb
    services.beta.kubernetes.io/aws-load-balancer-subnets: eksctl-hdo-test2-cluster/SubnetPublicAPNORTHEAST2C
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: hdoev-web-admin
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
