export const stationData = [
  {
    id: 3,
    category: 'STT_DIR',
    name: 'Sean 주유소',
    bizRegNo: '1234567890',
    address: '서울 강서구 화곡로68길 15, 아벨테크노지식산업센터',
    contactName: 'Sean',
    contactPhoneNo: '01090014560',
    contactEmail: 'sean@caelumglobal.com',
    deductType: 'NONE',
    discountPrice: 0,
    staticUnitPrice: 0,
    payMethodId: null,
    isPayLater: false,
    billingDate: null,
    closed: false,
    area: 14,
    branch: 17,
    haveCarWash: true,
    STN_STN_SEQ: null,
    STN_STN_ID: null,
    STN_STN_GUBUN: 'STT_DIR',
    STN_CUST_NO: null,
    STN_ASSGN_AREA_GUBUN: null,
    STN_COST_CT: null,
    STN_PAL_CT: null,
    STN_STN_SHORT_NM: null,
    createdAt: '2023-06-07 17:49:50',
    updatedAt: '2023-06-12 17:26:29',
    createdBy: {
      name: '배연진',
      id: '03018e6d-b51f-455b-8d2f-d360bba8ca22',
      accountId: 'sarc',
      retired: false,
      orgId: 0,
    },
    updatedBy: {
      name: '배연진',
      id: '03018e6d-b51f-455b-8d2f-d360bba8ca22',
      accountId: 'sarc',
      retired: false,
      orgId: 0,
    },
  },
  {
    id: 2,
    category: 'HDO',
    name: '현대오일뱅크',
    bizRegNo: null,
    address: null,
    contactName: null,
    contactPhoneNo: null,
    contactEmail: null,
    deductType: 'NONE',
    discountPrice: 0,
    staticUnitPrice: 0,
    payMethodId: null,
    isPayLater: false,
    billingDate: null,
    closed: false,
    area: null,
    branch: null,
    haveCarWash: false,
    STN_STN_SEQ: null,
    STN_STN_ID: null,
    STN_STN_GUBUN: null,
    STN_CUST_NO: null,
    STN_ASSGN_AREA_GUBUN: null,
    STN_COST_CT: null,
    STN_PAL_CT: null,
    STN_STN_SHORT_NM: null,
    createdAt: '2023-05-22 22:57:29',
    updatedAt: '2023-06-12 17:26:29',
    createdBy: {
      name: '배연진',
      id: '03018e6d-b51f-455b-8d2f-d360bba8ca22',
      accountId: 'sarc',
      retired: false,
      orgId: 0,
    },
    updatedBy: {
      name: '배연진',
      id: '03018e6d-b51f-455b-8d2f-d360bba8ca22',
      accountId: 'sarc',
      retired: false,
      orgId: 0,
    },
  },
  {
    id: 0,
    category: 'HDO',
    name: '개발용-NTCON',
    bizRegNo: null,
    address: null,
    contactName: null,
    contactPhoneNo: null,
    contactEmail: null,
    deductType: 'NONE',
    discountPrice: 0,
    staticUnitPrice: 0,
    payMethodId: null,
    isPayLater: false,
    billingDate: null,
    closed: false,
    area: null,
    branch: null,
    haveCarWash: false,
    STN_STN_SEQ: null,
    STN_STN_ID: null,
    STN_STN_GUBUN: null,
    STN_CUST_NO: null,
    STN_ASSGN_AREA_GUBUN: null,
    STN_COST_CT: null,
    STN_PAL_CT: null,
    STN_STN_SHORT_NM: null,
    createdAt: '2023-05-22 22:57:11',
    updatedAt: '2023-06-07 17:55:31',
    createdBy: {
      name: '배연진',
      id: '03018e6d-b51f-455b-8d2f-d360bba8ca22',
      accountId: 'sarc',
      retired: false,
      orgId: 0,
    },
    updatedBy: {
      name: '배연진',
      id: '03018e6d-b51f-455b-8d2f-d360bba8ca22',
      accountId: 'sarc',
      retired: false,
      orgId: 0,
    },
  },
  {
    id: 1,
    category: 'DEF',
    name: '일반이용자',
    bizRegNo: null,
    address: null,
    contactName: null,
    contactPhoneNo: null,
    contactEmail: null,
    deductType: 'NONE',
    discountPrice: 0,
    staticUnitPrice: 0,
    payMethodId: null,
    isPayLater: false,
    billingDate: null,
    closed: false,
    area: null,
    branch: null,
    haveCarWash: false,
    STN_STN_SEQ: null,
    STN_STN_ID: null,
    STN_STN_GUBUN: null,
    STN_CUST_NO: null,
    STN_ASSGN_AREA_GUBUN: null,
    STN_COST_CT: null,
    STN_PAL_CT: null,
    STN_STN_SHORT_NM: null,
    createdAt: '2023-05-22 22:57:11',
    updatedAt: '2023-06-07 12:28:38',
    createdBy: {
      name: '배연진',
      id: '03018e6d-b51f-455b-8d2f-d360bba8ca22',
      accountId: 'sarc',
      retired: false,
      orgId: 0,
    },
    updatedBy: {
      name: '배연진',
      id: '03018e6d-b51f-455b-8d2f-d360bba8ca22',
      accountId: 'sarc',
      retired: false,
      orgId: 0,
    },
  },
];
